%% singer aoto
%
%
% imwrite
clc;
baseFig = './basePic.jpg';
lyric = './liang.txt';
tcf('Aoto')
Ffig = figure('name','Aoto','Position',[40 100 500*1920/1080 500]);
A = imread(baseFig);
% Get interested area as background of lyrics
[BW] = roipoly(A);
[h,w] = find(BW==1);
% [left button width height]
SRC = imcrop(A,[1 min(h) size(A,2) max(h) - min(h)]);
imshow(SRC)
%%
% imshow(SRC)
tcf('Aoto')
Ffig = figure('name','Aoto','Position',[40 100 500*1920/1080 500]);
liang = ["曾经意外 他和她 相爱",...
    "在不会 犹豫的时代",...
    "以为明白",...
    "所以爱得痛快",...
    "一双手 紧紧放不开",...
    "心中的 执着与未来",...
    "忘不了 你的爱",...
    "但结局难更改",...
    "我没能把你留下来",...
    "更不像他能给你一个",...
    "期待的未来",...
    "幼稚的男孩",...
    "你的关怀一直随身携带",...
    "无人的地方再打开",...
    "想问你现在",...
    "是否忧伤不再",...
    "像躺在阳光下的海",...
    "像用心涂抹的色彩",...
    "让你微笑起来 勇敢起来",...
    "忘不了 你的爱",...
    "但结局难更改",...
    "我没能把你留下来",...
    "更不像他能给你一个",...
    "期待的未来",...
    "幼稚的男孩",...
    "想你就现在",...
    "想你 每当我又徘徊",...
    "所有遗憾的 都不是未来",...
    "所有爱最后都难免",...
    "逃不过伤害",...
    "不必再重来",...
    "现在我只希望疼痛来得更痛快",...
    "反正不能够重来"];
clc
SRC_1 = SRC;
% insert
for i=1:1:length(liang)
    if false
        cprintf('comments',liang(i));
    else
        position = [0 0];
        insertText(SRC_1,position,...
            '曾将',...
            'FontSize',15,...
            'AnchorPoint','center',...
            'Font','STKAITI',...
            'TextColor','black');
        cprintf('comments',liang(i));
        imshow(SRC_1,'Parent',gca)
    end
end


%%
clc;
for i=1:1:length(liang)
    cprintf('comments',strcat(liang(i),'\n'));
end